IMAGE_HEIGHT: 720
IMAGE_WIDTH: 1280
VIDEO_DEVICE:
  REAL: "/dev/video0"
  VIRTUAL: "/dev/video2"
DEVICE: "GPU"
EFFECTS:
  - name: "FACE_FOLLOW"
    enable: true
    args:
      scale: 0.8
      filter: 0.8
  - name: "BG_BLUR"
    enable: true
    args:
      kernel_size: 30
      dilate: 5
  - name: "BG_REMOVE"
    enable: true
    args:
      kernel_size: 20
      dilate: 15
  - name: "FLIP"
    enable: true
    args:
      horizontal: false
      vertical: false
  - name: LIGHT_ENHANCE
    enable: true
    args:
      level: 0.2
  - name: "FPS"
    enable: true
    args:
      flip: false
      scale: 1.5
      color: [255, 0, 0]