IMAGE_HEIGHT: 720
IMAGE_WIDTH: 1280
VIDEO_DEVICE:
  REAL: "/dev/video0"
  VIRTUAL: "/dev/video2"
DEVICE: "GPU"
EFFECTS:
  - name: "FACE_DETECTION"
    enable: true
  - name: "BG_BLUR"
    enable: false
    args:
      kernel_size: 30
      dilate: 5
  - name: "BG_REMOVE"
    enable: false
    args:
      inverted: false
      dilate: 5
  - name: "STYLE_TRANSFER"
    enable: false
    args:
      style: "mosaic"
  - name: "FLIP"
    enable: false
    args:
      horizontal: false
      vertical: false
  - name: "FPS"
    enable: true